export const defaultTimeline = {
  phases: [
    { label: "Concept", start: 1, end: 4 },
    { label: "Build", start: 5, end: 8 },
    { label: "Launch & Grow", start: 9, end: 12 },
  ],
  weeks: [
    { label: "Week 1", date: "Jan 05" },
    { label: "Week 2", date: "Jan 12" },
    { label: "Week 3", date: "Jan 19" },
    { label: "Week 4", date: "Jan 26" },
    { label: "Week 5", date: "Feb 02" },
    { label: "Week 6", date: "Feb 09" },
    { label: "Week 7", date: "Feb 16" },
    { label: "Week 8", date: "Feb 23" },
    { label: "Week 9", date: "Mar 02" },
    { label: "Week 10", date: "Mar 09" },
    { label: "Week 11", date: "Mar 16" },
    { label: "Week 12", date: "Mar 23" },
  ],
  tasks: [
    {
      name: "Discovery",
      start: 1,
      end: 2,
      color: "orange",
      note: "Goals, stakeholders and success metrics locked in.",
    },
    {
      name: "Prototype",
      start: 3,
      end: 5,
      color: "green",
      note: "A working prototype behind a clickable surface — no mocks.",
    },
    {
      name: "Validate",
      start: 5,
      end: 7,
      color: "teal",
      note: "Real users, real feedback — before the full build.",
    },
    {
      name: "Build",
      start: 6,
      end: 10,
      color: "orange",
      note: "Production code in weekly shippable increments.",
    },
    { name: "Launch", start: 9, end: 11, color: "blue", note: "Deploy, monitor, stabilize." },
    {
      name: "Grow",
      start: 11,
      end: 12,
      color: "green",
      note: "Measure, iterate, compound the wins.",
    },
  ],
};
